"""
create_mock_board.py
=====================
Creates the ESPN mock draft board CSV with 12-team pick notation.
py -3.12 create_mock_board.py
"""
import pandas as pd
import os

os.makedirs(os.path.join("data","2026"), exist_ok=True)

players = [
    ("Bijan Robinson", "RB", "ATL"),
    ("Jahmyr Gibbs", "RB", "DET"),
    ("Puka Nacua", "WR", "LAR"),
    ("Ja'Marr Chase", "WR", "CIN"),
    ("Christian McCaffrey", "RB", "SF"),
    ("Jaxon Smith-Njigba", "WR", "SEA"),
    ("Amon-Ra St. Brown", "WR", "DET"),
    ("Jonathan Taylor", "RB", "IND"),
    ("De'Von Achane", "RB", "MIA"),
    ("CeeDee Lamb", "WR", "DAL"),
    ("Ashton Jeanty", "RB", "LV"),
    ("Justin Jefferson", "WR", "MIN"),
    ("James Cook III", "RB", "BUF"),
    ("Jeremiyah Love", "RB", "ARI"),
    ("Drake London", "WR", "ATL"),
    ("Saquon Barkley", "RB", "PHI"),
    ("Rashee Rice", "WR", "KC"),
    ("Derrick Henry", "RB", "BAL"),
    ("Nico Collins", "WR", "HOU"),
    ("Omarion Hampton", "RB", "LAC"),
    ("Malik Nabers", "WR", "NYG"),
    ("Trey McBride", "TE", "ARI"),
    ("Josh Jacobs", "RB", "GB"),
    ("Brock Bowers", "TE", "LV"),
    ("Chase Brown", "RB", "CIN"),
    ("Chris Olave", "WR", "NO"),
    ("Breece Hall", "RB", "NYJ"),
    ("George Pickens", "WR", "DAL"),
    ("AJ Brown", "WR", "PHI"),
    ("Kenneth Walker III", "RB", "KC"),
    ("Garrett Wilson", "WR", "NYJ"),
    ("Tetairoa McMillan", "WR", "CAR"),
    ("DeVonta Smith", "WR", "PHI"),
    ("Javonte Williams", "RB", "DAL"),
    ("Kyren Williams", "RB", "LAR"),
    ("Travis Etienne Jr.", "RB", "NO"),
    ("Zay Flowers", "WR", "BAL"),
    ("Terry McLaurin", "WR", "WSH"),
    ("Cam Skattebo", "RB", "NYG"),
    ("Tee Higgins", "WR", "CIN"),
    ("Josh Allen", "QB", "BUF"),
    ("Davante Adams", "WR", "LAR"),
    ("Bucky Irving", "RB", "TB"),
    ("Carnell Tate", "WR", "TEN"),
    ("Colston Loveland", "TE", "CHI"),
    ("Quinshon Judkins", "RB", "CLE"),
    ("Lamar Jackson", "QB", "BAL"),
    ("Ladd McConkey", "WR", "LAC"),
    ("Emeka Egbuka", "WR", "TB"),
    ("Jaylen Waddle", "WR", "DEN"),
    ("Tyler Warren", "TE", "IND"),
    ("TreVeyon Henderson", "RB", "NE"),
    ("Jameson Williams", "WR", "DET"),
    ("Jadarian Price", "RB", "SEA"),
    ("DJ Moore", "WR", "BUF"),
    ("Luther Burden III", "WR", "CHI"),
    ("Jayden Daniels", "QB", "WSH"),
    ("Rome Odunze", "WR", "CHI"),
    ("Marvin Harrison Jr.", "WR", "ARI"),
    ("Bhayshul Tuten", "RB", "JAX"),
    ("D'Andre Swift", "RB", "CHI"),
    ("Harold Fannin Jr.", "TE", "CLE"),
    ("David Montgomery", "RB", "HOU"),
    ("Chuba Hubbard", "RB", "CAR"),
    ("Michael Pittman Jr.", "WR", "PIT"),
    ("Jordyn Tyson", "WR", "NO"),
    ("Drake Maye", "QB", "NE"),
    ("Joe Burrow", "QB", "CIN"),
    ("Jalen Hurts", "QB", "PHI"),
    ("Alec Pierce", "WR", "IND"),
    ("Kyle Pitts", "TE", "ATL"),
    ("DK Metcalf", "WR", "PIT"),
    ("Mike Evans", "WR", "SF"),
    ("Courtland Sutton", "WR", "DEN"),
    ("Tony Pollard", "RB", "TEN"),
    ("Aaron Jones Sr.", "RB", "MIN"),
    ("Sam LaPorta", "TE", "DET"),
    ("Jaxson Dart", "QB", "NYG"),
    ("Christian Watson", "WR", "GB"),
    ("Jaylen Warren", "RB", "PIT"),
    ("Chris Godwin Jr.", "WR", "TB"),
    ("Jakobi Meyers", "WR", "JAX"),
    ("Parker Washington", "WR", "JAX"),
    ("Brian Thomas Jr.", "WR", "JAX"),
    ("Kenneth Gainwell", "RB", "TB"),
    ("Wan'Dale Robinson", "WR", "TEN"),
    ("Rachaad White", "RB", "WSH"),
    ("Rico Dowdle", "RB", "PIT"),
    ("JK Dobbins", "RB", "DEN"),
    ("Makai Lemon", "WR", "PHI"),
    ("Rhamondre Stevenson", "RB", "NE"),
    ("Ricky Pearsall", "WR", "SF"),
    ("Matthew Golden", "WR", "GB"),
    ("Travis Kelce", "TE", "KC"),
    ("Michael Wilson", "WR", "ARI"),
    ("RJ Harvey", "RB", "DEN"),
    ("KC Concepcion", "WR", "CLE"),
    ("Kyle Monangai", "RB", "CHI"),
    ("Josh Downs", "WR", "IND"),
    ("Blake Corum", "RB", "LAR"),
    ("Jordan Addison", "WR", "MIN"),
    ("Brock Purdy", "QB", "SF"),
    ("Xavier Worthy", "WR", "KC"),
    ("Dak Prescott", "QB", "DAL"),
    ("Jonathon Brooks", "RB", "CAR"),
    ("George Kittle", "TE", "SF"),
    ("Dallas Goedert", "TE", "PHI"),
    ("Jake Ferguson", "TE", "DAL"),
    ("Khalil Shakir", "WR", "BUF"),
    ("Jacory Croskey-Merritt", "RB", "WSH"),
    ("Woody Marks", "RB", "HOU"),
    ("Tyjae Spears", "RB", "TEN"),
    ("Jayden Reed", "WR", "GB"),
    ("Zach Charbonnet", "RB", "SEA"),
    ("Isiah Pacheco", "RB", "DET"),
    ("Trevor Lawrence", "QB", "JAX"),
    ("Quentin Johnston", "WR", "LAC"),
    ("Romeo Doubs", "WR", "NE"),
    ("Tucker Kraft", "TE", "GB"),
    ("Alvin Kamara", "RB", "NO"),
    ("Jalen Coker", "WR", "CAR"),
    ("Jordan Mason", "RB", "MIN"),
    ("Omar Cooper Jr.", "WR", "NYJ"),
    ("Caleb Williams", "QB", "CHI"),
    ("Jayden Higgins", "WR", "HOU"),
    ("Jalen McMillan", "WR", "TB"),
    ("Bo Nix", "QB", "DEN"),
    ("Isaiah Likely", "TE", "NYG"),
    ("Chris Rodriguez Jr.", "RB", "JAX"),
    ("Calvin Ridley", "WR", "TEN"),
    ("Brandon Aubrey", "K", "DAL"),
    ("Tyler Allgeier", "RB", "ARI"),
    ("Texans D/ST", "DST", "HOU"),
    ("Broncos D/ST", "DST", "DEN"),
    ("Patrick Mahomes", "QB", "KC"),
    ("Jerry Jeudy", "WR", "CLE"),
    ("Justin Herbert", "QB", "LAC"),
    ("Tank Bigsby", "RB", "PHI"),
    ("Seahawks D/ST", "DST", "SEA"),
    ("Matthew Stafford", "QB", "LAR"),
    ("TJ Hockenson", "TE", "MIN"),
    ("Rashid Shaheed", "WR", "SEA"),
    ("Patriots D/ST", "DST", "NE"),
    ("Cameron Dicker", "K", "LAC"),
    ("Steelers D/ST", "DST", "PIT"),
    ("Eagles D/ST", "DST", "PHI"),
    ("Rams D/ST", "DST", "LAR"),
    ("Brian Robinson Jr.", "RB", "ATL"),
    ("Ravens D/ST", "DST", "BAL"),
    ("Ka'imi Fairbairn", "K", "HOU"),
    ("Jason Myers", "K", "SEA"),
    ("Germie Bernard", "WR", "PIT"),
    ("Chris Bell", "WR", "MIA"),
    ("Kenyon Sadiq", "TE", "NYJ"),
    ("Harrison Mevis", "K", "LAR"),
    ("Braelon Allen", "RB", "NYJ"),
    ("Jauan Jennings", "WR", "MIN"),
    ("Eddy Pineiro", "K", "SF"),
    ("Tyler Shough", "QB", "NO"),
    ("Cam Little", "K", "JAX"),
    ("Mark Andrews", "TE", "BAL"),
    ("Jake Bates", "K", "DET"),
    ("Vikings D/ST", "DST", "MIN"),
    ("Dalton Kincaid", "TE", "BUF"),
    ("Kyler Murray", "QB", "MIN"),
    ("Browns D/ST", "DST", "CLE"),
    ("Daniel Jones", "QB", "IND"),
    ("Jaguars D/ST", "DST", "JAX"),
    ("Harrison Butker", "K", "KC"),
    ("Tyler Loop", "K", "BAL"),
    ("Denzel Boston", "WR", "CLE"),
    ("Darnell Mooney", "WR", "NYG"),
    ("Lions D/ST", "DST", "DET"),
    ("Cairo Santos", "K", "CHI"),
    ("Will Reichard", "K", "MIN"),
    ("Chris Boswell", "K", "PIT"),
    ("James Conner", "RB", "ARI"),
    ("Stefon Diggs", "WR", "FA"),
    ("Travis Hunter", "WR", "JAX"),
    ("Antonio Williams", "WR", "WSH"),
    ("Chargers D/ST", "DST", "LAC"),
    ("Jalen Nailor", "WR", "LV"),
    ("Tre Tucker", "WR", "LV"),
    ("Tyrone Tracy Jr.", "RB", "NYG"),
    ("Mike Washington Jr.", "WR", "LV"),
]

rows = []
for i, (name, pos, team) in enumerate(players, 1):
    rd   = (i - 1) // 12 + 1
    pick = (i - 1) % 12 + 1
    pick_label = f"{rd}.{pick:02d}"
    rows.append({
        "pick":        i,
        "pick_label":  pick_label,
        "round":       rd,
        "pick_in_round": pick,
        "player":      name,
        "position":    pos,
        "team":        team,
    })

df = pd.DataFrame(rows)
path = os.path.join("data", "2026", "mock_board.csv")
df.to_csv(path, index=False)
print(f"✅ Mock board saved → {path}")
print(f"   {len(df)} picks · {df['round'].max()} rounds")
print(df.head(15).to_string(index=False))
