"""
create_mock_board.py
Generates data/2026/mock_board.csv from hardcoded FantasyPros PPR ADP data.
Source: https://www.fantasypros.com/nfl/adp/ppr-overall.php (ESPN PPR, 2026)
Run with: py -3.12 create_mock_board.py
"""

import csv
import os

# ── ADP DATA ─────────────────────────────────────────────────────────────────
# Format: (overall_rank, player_name, team, position, adp)
ADP_DATA = [
    (1,  "Jahmyr Gibbs",            "DET", "RB",  1.5),
    (2,  "Bijan Robinson",          "ATL", "RB",  1.5),
    (3,  "Ja'Marr Chase",           "CIN", "WR",  3.0),
    (4,  "Puka Nacua",              "LAR", "WR",  4.0),
    (5,  "Jaxon Smith-Njigba",      "SEA", "WR",  5.0),
    (6,  "Christian McCaffrey",     "SF",  "RB",  6.0),
    (7,  "Jonathan Taylor",         "IND", "RB",  7.5),
    (8,  "Amon-Ra St. Brown",       "DET", "WR",  7.5),
    (9,  "CeeDee Lamb",             "DAL", "WR",  10.0),
    (10, "James Cook III",          "BUF", "RB",  10.5),
    (11, "Justin Jefferson",        "MIN", "WR",  11.0),
    (12, "Ashton Jeanty",           "LV",  "RB",  11.0),
    (13, "De'Von Achane",           "MIA", "RB",  12.5),
    (14, "Saquon Barkley",          "PHI", "RB",  15.0),
    (15, "Omarion Hampton",         "LAC", "RB",  16.5),
    (16, "Kenneth Walker III",      "KC",  "RB",  16.5),
    (17, "Chase Brown",             "CIN", "RB",  16.5),
    (18, "Rashee Rice",             "KC",  "WR",  18.5),
    (19, "Drake London",            "ATL", "WR",  18.5),
    (20, "Trey McBride",            "ARI", "TE",  19.5),
    (21, "Jeremiyah Love",          "ARI", "RB",  21.5),
    (22, "Derrick Henry",           "BAL", "RB",  21.5),
    (23, "Brock Bowers",            "LV",  "TE",  22.0),
    (24, "Nico Collins",            "HOU", "WR",  25.0),
    (25, "Malik Nabers",            "NYG", "WR",  25.0),
    (26, "George Pickens",          "DAL", "WR",  26.0),
    (27, "A.J. Brown",              "PHI", "WR",  28.0),
    (28, "Josh Jacobs",             "GB",  "RB",  28.0),
    (29, "Josh Allen",              "BUF", "QB",  29.0),
    (30, "Chris Olave",             "NO",  "WR",  29.5),
    (31, "Kyren Williams",          "LAR", "RB",  32.0),
    (32, "Breece Hall",             "NYJ", "RB",  32.0),
    (33, "Travis Etienne Jr.",      "NO",  "RB",  33.5),
    (34, "DeVonta Smith",           "PHI", "WR",  35.0),
    (35, "Garrett Wilson",          "NYJ", "WR",  35.5),
    (36, "Tetairoa McMillan",       "CAR", "WR",  35.5),
    (37, "Javonte Williams",        "DAL", "RB",  36.0),
    (38, "Tee Higgins",             "CIN", "WR",  37.0),
    (39, "Zay Flowers",             "BAL", "WR",  37.5),
    (40, "Ladd McConkey",           "LAC", "WR",  40.5),
    (41, "Bucky Irving",            "TB",  "RB",  43.0),
    (42, "Emeka Egbuka",            "TB",  "WR",  43.5),
    (43, "Luther Burden III",       "CHI", "WR",  43.5),
    (44, "Colston Loveland",        "CHI", "TE",  44.5),
    (45, "Cam Skattebo",            "NYG", "RB",  45.0),
    (46, "TreVeyon Henderson",      "NE",  "RB",  47.5),
    (47, "Lamar Jackson",           "BAL", "QB",  48.0),
    (48, "Davante Adams",           "LAR", "WR",  48.0),
    (49, "David Montgomery",        "HOU", "RB",  50.0),
    (50, "Terry McLaurin",          "WAS", "WR",  51.5),
    (51, "Jameson Williams",        "DET", "WR",  51.5),
    (52, "Jaylen Waddle",           "DEN", "WR",  52.0),
    (53, "D'Andre Swift",           "CHI", "RB",  53.0),
    (54, "DJ Moore",                "BUF", "WR",  54.0),
    (55, "Quinshon Judkins",        "CLE", "RB",  54.0),
    (56, "Mike Evans",              "SF",  "WR",  56.5),
    (57, "Rome Odunze",             "CHI", "WR",  57.0),
    (58, "Joe Burrow",              "CIN", "QB",  57.5),
    (59, "Christian Watson",        "GB",  "WR",  57.5),
    (60, "Drake Maye",              "NE",  "QB",  58.0),
    (61, "Jadarian Price",          "SEA", "RB",  62.0),
    (62, "Bhayshul Tuten",          "JAC", "RB",  62.0),
    (63, "Chuba Hubbard",           "CAR", "RB",  63.5),
    (64, "Carnell Tate",            "TEN", "WR",  63.5),
    (65, "Jayden Daniels",          "WAS", "QB",  64.0),
    (66, "Tyler Warren",            "IND", "TE",  64.5),
    (67, "Marvin Harrison Jr.",     "ARI", "WR",  67.5),
    (68, "Caleb Williams",          "CHI", "QB",  69.0),
    (69, "Jalen Hurts",             "PHI", "QB",  70.5),
    (70, "Jordyn Tyson",            "NO",  "WR",  72.0),
    (71, "Jaylen Warren",           "PIT", "RB",  74.0),
    (72, "Brian Thomas Jr.",        "JAC", "WR",  75.0),
    (73, "DK Metcalf",              "PIT", "WR",  75.0),
    (74, "RJ Harvey",               "DEN", "RB",  75.5),
    (75, "Parker Washington",       "JAC", "WR",  76.0),
    (76, "Alec Pierce",             "IND", "WR",  76.5),
    (77, "Courtland Sutton",        "DEN", "WR",  77.5),
    (78, "Rhamondre Stevenson",     "NE",  "RB",  78.0),
    (79, "Trevor Lawrence",         "JAC", "QB",  78.5),
    (80, "Dak Prescott",            "DAL", "QB",  79.0),
    (81, "Justin Herbert",          "LAC", "QB",  79.5),
    (82, "Tony Pollard",            "TEN", "RB",  80.0),
    (83, "Harold Fannin Jr.",       "CLE", "TE",  81.5),
    (84, "Jaxson Dart",             "NYG", "QB",  82.0),
    (85, "Makai Lemon",             "PHI", "WR",  84.0),
    (86, "Tucker Kraft",            "GB",  "TE",  84.0),
    (87, "Michael Wilson",          "ARI", "WR",  86.0),
    (88, "Rico Dowdle",             "PIT", "RB",  89.0),
    (89, "Patrick Mahomes II",      "KC",  "QB",  92.0),
    (90, "Kyle Monangai",           "CHI", "RB",  93.0),
    (91, "Chris Godwin Jr.",        "TB",  "WR",  93.5),
    (92, "Matthew Stafford",        "LAR", "QB",  93.5),
    (93, "Jakobi Meyers",           "JAC", "WR",  93.5),
    (94, "Brock Purdy",             "SF",  "QB",  94.0),
    (95, "Ricky Pearsall",          "SF",  "WR",  96.0),
    (96, "Sam LaPorta",             "DET", "TE",  96.5),
    (97, "Jayden Reed",             "GB",  "WR",  97.0),
    (98, "Kyle Pitts Sr.",          "ATL", "TE",  97.5),
    (99, "Quentin Johnston",        "LAC", "WR",  97.5),
    (100,"Jordan Addison",          "MIN", "WR",  99.0),
    (101,"Bo Nix",                  "DEN", "QB",  99.5),
    (102,"Michael Pittman Jr.",     "PIT", "WR",  100.0),
    (103,"Jared Goff",              "DET", "QB",  100.5),
    (104,"Blake Corum",             "LAR", "RB",  103.0),
    (105,"J.K. Dobbins",            "DEN", "RB",  104.5),
    (106,"Kenneth Gainwell",        "TB",  "RB",  105.0),
    (107,"Tyler Shough",            "NO",  "QB",  105.5),
    (108,"Josh Downs",              "IND", "WR",  107.0),
    (109,"Jordan Love",             "GB",  "QB",  108.0),
    (110,"Wan'Dale Robinson",       "TEN", "WR",  108.0),
    (111,"Kyler Murray",            "MIN", "QB",  108.5),
    (112,"Baker Mayfield",          "TB",  "QB",  111.0),
    (113,"Romeo Doubs",             "NE",  "WR",  115.0),
    (114,"Khalil Shakir",           "BUF", "WR",  118.5),
    (115,"George Kittle",           "SF",  "TE",  118.5),
    (116,"Matthew Golden",          "GB",  "WR",  119.0),
    (117,"Jacory Croskey-Merritt",  "WAS", "RB",  121.5),
    (118,"Malik Willis",            "MIA", "QB",  121.5),
    (119,"Jake Ferguson",           "DAL", "TE",  122.0),
    (120,"Travis Kelce",            "KC",  "TE",  122.5),
    (121,"Rachaad White",           "WAS", "RB",  122.5),
    (122,"Jordan Mason",            "MIN", "RB",  123.0),
    (123,"KC Concepcion",           "CLE", "WR",  123.5),
    (124,"Aaron Jones Sr.",         "MIN", "RB",  124.0),
    (125,"Xavier Worthy",           "KC",  "WR",  124.5),
    (126,"Jayden Higgins",          "HOU", "WR",  124.5),
    (127,"Jalen Coker",             "CAR", "WR",  125.0),
    (128,"Chris Rodriguez Jr.",     "JAC", "RB",  125.5),
    (129,"Oronde Gadsden II",       "LAC", "TE",  128.5),
    (130,"Isaiah Likely",           "NYG", "TE",  128.5),
    (131,"Dallas Goedert",          "PHI", "TE",  130.0),
    (132,"Dalton Kincaid",          "BUF", "TE",  130.0),
    (133,"Sam Darnold",             "SEA", "QB",  131.5),
    (134,"Jonathon Brooks",         "CAR", "RB",  133.0),
    (135,"C.J. Stroud",             "HOU", "QB",  133.0),
    (136,"Tyrone Tracy Jr.",        "NYG", "RB",  133.5),
    (137,"Cam Ward",                "TEN", "QB",  135.0),
    (138,"Mark Andrews",            "BAL", "TE",  138.0),
    (139,"Daniel Jones",            "IND", "QB",  140.0),
    (140,"Bryce Young",             "CAR", "QB",  143.0),
    (141,"Tyler Allgeier",          "ARI", "RB",  145.0),
    (142,"Jauan Jennings",          "MIN", "WR",  145.5),
    (143,"Juwan Johnson",           "NO",  "TE",  146.0),
    (144,"Woody Marks",             "HOU", "RB",  146.5),
    (145,"Jalen McMillan",          "TB",  "WR",  148.0),
    (146,"Stefon Diggs",            "FA",  "WR",  148.0),
    (147,"Kenyon Sadiq",            "NYJ", "TE",  149.0),
    (148,"Rashid Shaheed",          "SEA", "WR",  149.0),
    (149,"Brenton Strange",         "JAC", "TE",  152.0),
    (150,"Isiah Pacheco",           "DET", "RB",  153.0),
    (151,"Jonah Coleman",           "DEN", "RB",  153.5),
    (152,"Hunter Henry",            "NE",  "TE",  154.0),
    (153,"Dylan Sampson",           "CLE", "RB",  155.0),
    (154,"Tyjae Spears",            "TEN", "RB",  155.5),
    (155,"Keaton Mitchell",         "LAC", "RB",  156.0),
    (156,"Omar Cooper Jr.",         "NYJ", "WR",  156.0),
    (157,"Tre Tucker",              "LV",  "WR",  156.0),
    (158,"Chig Okonkwo",            "WAS", "TE",  157.5),
    (159,"Deebo Samuel Sr.",        "FA",  "WR",  161.5),
    (160,"Jalen Nailor",            "LV",  "WR",  165.0),
    (161,"T.J. Hockenson",          "MIN", "TE",  166.0),
    (162,"Denzel Boston",           "CLE", "WR",  166.0),
    (163,"Zach Charbonnet",         "SEA", "RB",  168.0),
    (164,"Emmett Johnson",          "KC",  "RB",  169.5),
    (165,"Dalton Schultz",          "HOU", "TE",  170.5),
    (166,"Brian Robinson Jr.",      "ATL", "RB",  174.0),
    (167,"Brandon Aiyuk",           "SF",  "WR",  174.0),
    (168,"Emanuel Wilson",          "SEA", "RB",  174.5),
    (169,"Alvin Kamara",            "NO",  "RB",  175.5),
    (170,"AJ Barner",               "SEA", "TE",  177.0),
    (171,"Tre' Harris",             "LAC", "WR",  179.0),
    (172,"Jerry Jeudy",             "CLE", "WR",  181.0),
    (173,"Kaytron Allen",           "WAS", "RB",  184.5),
    (174,"Tank Bigsby",             "PHI", "RB",  186.5),
    (175,"Ryan Flournoy",           "DAL", "WR",  188.5),
    (176,"Gunnar Helm",             "TEN", "TE",  191.0),
    (177,"Nicholas Singleton",      "TEN", "RB",  192.0),
    (178,"Kimani Vidal",            "LAC", "RB",  193.5),
    (179,"James Conner",            "ARI", "RB",  196.5),
    (180,"Cade Otton",              "TB",  "TE",  197.0),
    (181,"Pat Freiermuth",          "PIT", "TE",  198.5),
    (182,"Calvin Ridley",           "TEN", "WR",  200.0),
    (183,"Braelon Allen",           "NYJ", "RB",  201.0),
    (184,"David Njoku",             "LAC", "TE",  202.0),
    (185,"Troy Franklin",           "DEN", "WR",  205.5),
    (186,"Ray Davis",               "BUF", "RB",  206.0),
    (187,"Colby Parkinson",         "LAR", "TE",  206.5),
    (188,"Sean Tucker",             "TB",  "RB",  208.5),
    (189,"Tank Dell",               "HOU", "WR",  213.5),
    (190,"Houston Texans DST",      "HOU", "DST", 135.0),
    (191,"Seattle Seahawks DST",    "SEA", "DST", 149.0),
    (192,"Denver Broncos DST",      "DEN", "DST", 152.0),
    (193,"Los Angeles Rams DST",    "LAR", "DST", 161.0),
    (194,"Cleveland Browns DST",    "CLE", "DST", 175.0),
    (195,"Minnesota Vikings DST",   "MIN", "DST", 179.0),
    (196,"New England Patriots DST","NE",  "DST", 180.0),
    (197,"Philadelphia Eagles DST", "PHI", "DST", 185.0),
    (198,"Jacksonville Jaguars DST","JAC", "DST", 187.0),
    (199,"Pittsburgh Steelers DST", "PIT", "DST", 188.0),
    (200,"Los Angeles Chargers DST","LAC", "DST", 193.0),
]

TEAM_SIZE = 12  # 12-team snake draft

def build_mock_board(data, team_size=12):
    # Sort by ADP, use original rank as tiebreaker
    sorted_data = sorted(data, key=lambda x: (x[4], x[0]))
    rows = []
    for i, (rank, player, team, position, adp) in enumerate(sorted_data):
        pick_num = i + 1
        round_num = (pick_num - 1) // team_size + 1
        pos_in_round = (pick_num - 1) % team_size + 1
        # Snake: even rounds go in reverse
        pick_in_round = pos_in_round if round_num % 2 == 1 else team_size - pos_in_round + 1
        rows.append({
            "round":        round_num,
            "pick_in_round": pick_in_round,
            "overall_pick": pick_num,
            "player":       player,
            "position":     position,
            "team":         team,
            "adp":          adp,
        })
    return rows

if __name__ == "__main__":
    out_dir = os.path.join("data", "2026")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "mock_board.csv")

    rows = build_mock_board(ADP_DATA, TEAM_SIZE)

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["round","pick_in_round","overall_pick","player","position","team","adp"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"✓ Wrote {len(rows)} players → {out_path}")
    print(f"  Rounds: {rows[-1]['round']}  |  Team size: {TEAM_SIZE}")
    print("\nFirst 5 picks:")
    for r in rows[:5]:
        print(f"  {r['round']}.{r['pick_in_round']:02d}  {r['player']:30} {r['position']} {r['team']}")
