"""
create_yahoo_rankings.py
=========================
Yahoo Sports / Justin Boone 2026 PPR Rankings (May 2026 update, Top 190).
py -3.12 create_yahoo_rankings.py
"""
import pandas as pd
import os

os.makedirs(os.path.join("data","2026"), exist_ok=True)

players = [
    (1,  "Bijan Robinson",        "RB",  "ATL"),
    (2,  "Jahmyr Gibbs",          "RB",  "DET"),
    (3,  "Ja'Marr Chase",         "WR",  "CIN"),
    (4,  "Jaxon Smith-Njigba",    "WR",  "SEA"),
    (5,  "Puka Nacua",            "WR",  "LAR"),
    (6,  "Jonathan Taylor",       "RB",  "IND"),
    (7,  "Christian McCaffrey",   "RB",  "SF"),
    (8,  "James Cook III",        "RB",  "BUF"),
    (9,  "CeeDee Lamb",           "WR",  "DAL"),
    (10, "Amon-Ra St. Brown",     "WR",  "DET"),
    (11, "Chase Brown",           "RB",  "CIN"),
    (12, "Rashee Rice",           "WR",  "KC"),
    (13, "Ashton Jeanty",         "RB",  "LV"),
    (14, "De'Von Achane",         "RB",  "MIA"),
    (15, "Omarion Hampton",       "RB",  "LAC"),
    (16, "Saquon Barkley",        "RB",  "PHI"),
    (17, "Jeremiyah Love",        "RB",  "ARI"),
    (18, "Kenneth Walker III",    "RB",  "KC"),
    (19, "Justin Jefferson",      "WR",  "MIN"),
    (20, "Drake London",          "WR",  "ATL"),
    (21, "Brock Bowers",          "TE",  "LV"),
    (22, "Nico Collins",          "WR",  "HOU"),
    (23, "Josh Jacobs",           "RB",  "GB"),
    (24, "Trey McBride",          "TE",  "ARI"),
    (25, "Josh Allen",            "QB",  "BUF"),
    (26, "Derrick Henry",         "RB",  "BAL"),
    (27, "George Pickens",        "WR",  "DAL"),
    (28, "Kyren Williams",        "RB",  "LAR"),
    (29, "Javonte Williams",      "RB",  "DAL"),
    (30, "A.J. Brown",            "WR",  "PHI"),
    (31, "Chris Olave",           "WR",  "NO"),
    (32, "DeVonta Smith",         "WR",  "PHI"),
    (33, "Travis Etienne Jr.",    "RB",  "NO"),
    (34, "Breece Hall",           "RB",  "NYJ"),
    (35, "Malik Nabers",          "WR",  "NYG"),
    (36, "Tetairoa McMillan",     "WR",  "CAR"),
    (37, "Tee Higgins",           "WR",  "CIN"),
    (38, "Davante Adams",         "WR",  "LAR"),
    (39, "Luther Burden III",     "WR",  "CHI"),
    (40, "Lamar Jackson",         "QB",  "BAL"),
    (41, "Garrett Wilson",        "WR",  "NYJ"),
    (42, "Chuba Hubbard",         "RB",  "CAR"),
    (43, "Zay Flowers",           "WR",  "BAL"),
    (44, "Ladd McConkey",         "WR",  "LAC"),
    (45, "Bucky Irving",          "RB",  "TB"),
    (46, "Cam Skattebo",          "RB",  "NYG"),
    (47, "Colston Loveland",      "TE",  "CHI"),
    (48, "D'Andre Swift",         "RB",  "CHI"),
    (49, "Terry McLaurin",        "WR",  "WSH"),
    (50, "Jaylen Waddle",         "WR",  "DEN"),
    (51, "TreVeyon Henderson",    "RB",  "NE"),
    (52, "Carnell Tate",          "WR",  "TEN"),
    (53, "Christian Watson",      "WR",  "GB"),
    (54, "Tyler Warren",          "TE",  "IND"),
    (55, "Jameson Williams",      "WR",  "DET"),
    (56, "Drake Maye",            "QB",  "NE"),
    (57, "Jayden Daniels",        "QB",  "WSH"),
    (58, "Joe Burrow",            "QB",  "CIN"),
    (59, "Emeka Egbuka",          "WR",  "TB"),
    (60, "Makai Lemon",           "WR",  "PHI"),
    (61, "Jordyn Tyson",          "WR",  "NO"),
    (62, "DJ Moore",              "WR",  "BUF"),
    (63, "Quinshon Judkins",      "RB",  "CLE"),
    (64, "Bhayshul Tuten",        "RB",  "JAX"),
    (65, "David Montgomery",      "RB",  "HOU"),
    (66, "Tucker Kraft",          "TE",  "GB"),
    (67, "Rome Odunze",           "WR",  "CHI"),
    (68, "Jalen Hurts",           "QB",  "PHI"),
    (69, "Justin Herbert",        "QB",  "LAC"),
    (70, "Mike Evans",            "WR",  "SF"),
    (71, "Alec Pierce",           "WR",  "IND"),
    (72, "Jadarian Price",        "RB",  "SEA"),
    (73, "Jaylen Warren",         "RB",  "PIT"),
    (74, "Tony Pollard",          "RB",  "TEN"),
    (75, "Chris Godwin Jr.",      "WR",  "TB"),
    (76, "DK Metcalf",            "WR",  "PIT"),
    (77, "Courtland Sutton",      "WR",  "DEN"),
    (78, "Marvin Harrison Jr.",   "WR",  "ARI"),
    (79, "Michael Wilson",        "WR",  "ARI"),
    (80, "Rhamondre Stevenson",   "RB",  "NE"),
    (81, "Rico Dowdle",           "RB",  "PIT"),
    (82, "Kyle Monangai",         "RB",  "CHI"),
    (83, "Blake Corum",           "RB",  "LAR"),
    (84, "Parker Washington",     "WR",  "JAX"),
    (85, "Caleb Williams",        "QB",  "CHI"),
    (86, "Jaxson Dart",           "QB",  "NYG"),
    (87, "Harold Fannin Jr.",     "TE",  "CLE"),
    (88, "Kyle Pitts",            "TE",  "ATL"),
    (89, "Ricky Pearsall",        "WR",  "SF"),
    (90, "Dak Prescott",          "QB",  "DAL"),
    (91, "J.K. Dobbins",          "RB",  "DEN"),
    (92, "Bo Nix",                "QB",  "DEN"),
    (93, "Sam LaPorta",           "TE",  "DET"),
    (94, "Trevor Lawrence",       "QB",  "JAX"),
    (95, "Jakobi Meyers",         "WR",  "JAX"),
    (96, "Travis Kelce",          "TE",  "KC"),
    (97, "RJ Harvey",             "RB",  "DEN"),
    (98, "Jacory Croskey-Merritt","RB",  "WSH"),
    (99, "Wan'Dale Robinson",     "WR",  "TEN"),
    (100,"Rachaad White",         "RB",  "WSH"),
    (101,"Brian Thomas Jr.",      "WR",  "JAX"),
    (102,"Jayden Reed",           "WR",  "GB"),
    (103,"Jordan Addison",        "WR",  "MIN"),
    (104,"Kenneth Gainwell",      "RB",  "TB"),
    (105,"Chris Rodriguez Jr.",   "RB",  "JAX"),
    (106,"Isaiah Likely",         "TE",  "NYG"),
    (107,"Aaron Jones Sr.",       "RB",  "MIN"),
    (108,"KC Concepcion",         "WR",  "CLE"),
    (109,"Michael Pittman Jr.",   "WR",  "PIT"),
    (110,"Quentin Johnston",      "WR",  "LAC"),
    (111,"Brock Purdy",           "QB",  "SF"),
    (112,"Jordan Mason",          "RB",  "MIN"),
    (113,"Jalen Coker",           "WR",  "CAR"),
    (114,"Josh Downs",            "WR",  "IND"),
    (115,"Kyler Murray",          "QB",  "MIN"),
    (116,"Dalton Kincaid",        "TE",  "BUF"),
    (117,"George Kittle",         "TE",  "SF"),
    (118,"Tyrone Tracy Jr.",      "RB",  "NYG"),
    (119,"Romeo Doubs",           "WR",  "NE"),
    (120,"Stefon Diggs",          "WR",  "FA"),
    (121,"Omar Cooper Jr.",       "WR",  "NYJ"),
    (122,"Jayden Higgins",        "WR",  "HOU"),
    (123,"Jalen McMillan",        "WR",  "TB"),
    (124,"Jake Ferguson",         "TE",  "DAL"),
    (125,"Patrick Mahomes",       "QB",  "KC"),
    (126,"Jonah Coleman",         "RB",  "DEN"),
    (127,"Tyler Allgeier",        "RB",  "ARI"),
    (128,"Jonathon Brooks",       "RB",  "CAR"),
    (129,"Keaton Mitchell",       "RB",  "LAC"),
    (130,"Nicholas Singleton",    "RB",  "TEN"),
    (131,"Kaytron Allen",         "RB",  "WSH"),
    (132,"Brian Robinson Jr.",    "RB",  "ATL"),
    (133,"Emmett Johnson",        "RB",  "KC"),
    (134,"Zach Charbonnet",       "RB",  "SEA"),
    (135,"Travis Hunter",         "WR",  "JAX"),
    (136,"Dallas Goedert",        "TE",  "PHI"),
    (137,"Hunter Henry",          "TE",  "NE"),
    (138,"Xavier Worthy",         "WR",  "KC"),
    (139,"Isiah Pacheco",         "RB",  "DET"),
    (140,"Dylan Sampson",         "RB",  "CLE"),
    (141,"Woody Marks",           "RB",  "HOU"),
    (142,"Emanuel Wilson",        "RB",  "SEA"),
    (143,"Braelon Allen",         "RB",  "NYJ"),
    (144,"Chig Okonkwo",          "TE",  "WSH"),
    (145,"Denzel Boston",         "WR",  "CLE"),
    (146,"Khalil Shakir",         "WR",  "BUF"),
    (147,"Matthew Golden",        "WR",  "GB"),
    (148,"Mark Andrews",          "TE",  "BAL"),
    (149,"Tank Bigsby",           "RB",  "PHI"),
    (150,"Ray Davis",             "RB",  "BUF"),
    (151,"Matthew Stafford",      "QB",  "LAR"),
    (152,"Tyler Shough",          "QB",  "NO"),
    (153,"Rashid Shaheed",        "WR",  "SEA"),
    (154,"Jauan Jennings",        "WR",  "MIN"),
    (155,"Deebo Samuel Sr.",      "WR",  "FA"),
    (156,"Tre Tucker",            "WR",  "LV"),
    (157,"Jalen Nailor",          "WR",  "LV"),
    (158,"Antonio Williams",      "WR",  "WSH"),
    (159,"Malik Willis",          "QB",  "MIA"),
    (160,"Demond Claiborne",      "RB",  "MIN"),
    (161,"Mike Washington Jr.",   "RB",  "LV"),
    (162,"Jaylen Wright",         "RB",  "MIA"),
    (163,"Jared Goff",            "QB",  "DET"),
    (164,"Baker Mayfield",        "QB",  "TB"),
    (165,"Jordan Love",           "QB",  "GB"),
    (166,"Brenton Strange",       "TE",  "JAX"),
    (167,"Oronde Gadsden II",     "TE",  "LAC"),
    (168,"Tyjae Spears",          "RB",  "TEN"),
    (169,"Najee Harris",          "RB",  "LAC"),
    (170,"Jordan James",          "RB",  "SF"),
    (171,"James Conner",          "RB",  "ARI"),
    (172,"Alvin Kamara",          "RB",  "NO"),
    (173,"Brandon Aiyuk",         "WR",  "SF"),
    (174,"Houston Texans",        "DST", "HOU"),
    (175,"Sean Tucker",           "RB",  "TB"),
    (176,"Jaydon Blue",           "RB",  "DAL"),
    (177,"Chris Brooks",          "RB",  "GB"),
    (178,"Seattle Seahawks",      "DST", "SEA"),
    (179,"Brandon Aubrey",        "K",   "DAL"),
    (180,"Justice Hill",          "RB",  "BAL"),
    (181,"Kaelon Black",          "RB",  "SF"),
    (182,"Sam Darnold",           "QB",  "SEA"),
    (183,"Denver Broncos",        "DST", "DEN"),
    (184,"Kayshon Boutte",        "WR",  "NE"),
    (185,"Adonai Mitchell",       "WR",  "NYJ"),
    (186,"Jerry Jeudy",           "WR",  "CLE"),
    (187,"Isaac TeSlaa",          "WR",  "DET"),
    (188,"Malik Washington",      "WR",  "MIA"),
    (189,"Pat Bryant",            "WR",  "DEN"),
    (190,"Ryan Flournoy",         "WR",  "DAL"),
]

rows = []
for rank, name, pos, team in players:
    rows.append({"player": name, "position": pos, "team": team,
                 "yahoo_rank": rank})

df = pd.DataFrame(rows)
df["yahoo_pos_rank"] = df.groupby("position")["yahoo_rank"].rank(method="first").astype(int)

path = os.path.join("data","2026","yahoo.csv")
df.to_csv(path, index=False)
print(f"✅ Yahoo rankings saved → {path}")
print(f"   {len(df)} players")
print(df.head(10).to_string(index=False))
