"""
create_rotoballer.py
=====================
Updated RotoBaller tiered PPR rankings.
py -3.12 create_rotoballer.py
"""
import pandas as pd
import os

os.makedirs(os.path.join("data","2026"), exist_ok=True)

# Format: (rank, name, position, team)
players = [
    # Tier 1
    (1, "Jahmyr Gibbs", "RB", "DET"),
    (2, "Bijan Robinson", "RB", "ATL"),
    (3, "Puka Nacua", "WR", "LAR"),
    (4, "Ja'Marr Chase", "WR", "CIN"),
    (5, "Jaxon Smith-Njigba", "WR", "SEA"),
    # Tier 2
    (6, "Christian McCaffrey", "RB", "SF"),
    (7, "Jonathan Taylor", "RB", "IND"),
    (8, "CeeDee Lamb", "WR", "DAL"),
    (9, "Amon-Ra St. Brown", "WR", "DET"),
    (10, "James Cook III", "RB", "BUF"),
    (11, "Justin Jefferson", "WR", "MIN"),
    (12, "Saquon Barkley", "RB", "PHI"),
    (13, "De'Von Achane", "RB", "MIA"),
    (14, "Ashton Jeanty", "RB", "LV"),
    (15, "Derrick Henry", "RB", "BAL"),
    (16, "Drake London", "WR", "ATL"),
    # Tier 3
    (17, "Kenneth Walker III", "RB", "SEA"),
    (18, "Malik Nabers", "WR", "NYG"),
    (19, "Trey McBride", "TE", "ARI"),
    (20, "Omarion Hampton", "RB", "LAC"),
    (21, "Chase Brown", "RB", "CIN"),
    (22, "Rashee Rice", "WR", "KC"),
    (23, "Nico Collins", "WR", "HOU"),
    (24, "George Pickens", "WR", "DAL"),
    # Tier 4
    (25, "Brock Bowers", "TE", "LV"),
    (26, "Jeremiyah Love", "RB", "ARI"),
    (27, "Josh Jacobs", "RB", "GB"),
    (28, "Kyren Williams", "RB", "LAR"),
    (29, "Chris Olave", "WR", "NO"),
    (30, "Josh Allen", "QB", "BUF"),
    (31, "A.J. Brown", "WR", "PHI"),
    (32, "DeVonta Smith", "WR", "PHI"),
    (33, "Travis Etienne Jr.", "RB", "JAX"),
    (34, "Tee Higgins", "WR", "CIN"),
    (35, "Tetairoa McMillan", "WR", "CAR"),
    (36, "Javonte Williams", "RB", "DAL"),
    # Tier 5
    (37, "Garrett Wilson", "WR", "NYJ"),
    (38, "Bucky Irving", "RB", "TB"),
    (39, "Davante Adams", "WR", "LAR"),
    (40, "Breece Hall", "RB", "NYJ"),
    (41, "Zay Flowers", "WR", "BAL"),
    (42, "Luther Burden III", "WR", "CHI"),
    (43, "Ladd McConkey", "WR", "LAC"),
    (44, "D'Andre Swift", "RB", "CHI"),
    (45, "Terry McLaurin", "WR", "WSH"),
    (46, "Jameson Williams", "WR", "DET"),
    (47, "Lamar Jackson", "QB", "BAL"),
    (48, "Colston Loveland", "TE", "CHI"),
    (49, "Jaylen Waddle", "WR", "MIA"),
    (50, "Emeka Egbuka", "WR", "TB"),
    (51, "Mike Evans", "WR", "TB"),
    (52, "Cam Skattebo", "RB", "NYG"),
    (53, "DJ Moore", "WR", "BUF"),
    # Tier 6
    (54, "David Montgomery", "RB", "HOU"),
    (55, "TreVeyon Henderson", "RB", "NE"),
    (56, "Quinshon Judkins", "RB", "CLE"),
    (57, "Bhayshul Tuten", "RB", "JAX"),
    (58, "Jayden Daniels", "QB", "WSH"),
    (59, "Jadarian Price", "RB", "SEA"),
    (60, "Christian Watson", "WR", "GB"),
    (61, "Carnell Tate", "WR", "TEN"),
    (62, "Alec Pierce", "WR", "IND"),
    (63, "Drake Maye", "QB", "NE"),
    # Tier 7
    (64, "Chuba Hubbard", "RB", "CAR"),
    (65, "Courtland Sutton", "WR", "DEN"),
    (66, "Jordyn Tyson", "WR", "NO"),
    (67, "Tyler Warren", "TE", "IND"),
    (68, "RJ Harvey", "RB", "DEN"),
    (69, "Parker Washington", "WR", "JAX"),
    (70, "Marvin Harrison Jr.", "WR", "ARI"),
    (71, "DK Metcalf", "WR", "PIT"),
    (72, "Rhamondre Stevenson", "RB", "NE"),
    (73, "Tony Pollard", "RB", "TEN"),
    (74, "Joe Burrow", "QB", "CIN"),
    (75, "Jalen Hurts", "QB", "PHI"),
    (76, "Rome Odunze", "WR", "CHI"),
    (77, "Michael Wilson", "WR", "ARI"),
    (78, "Rico Dowdle", "RB", "CAR"),
    (79, "Caleb Williams", "QB", "CHI"),
    (80, "Brian Thomas Jr.", "WR", "JAX"),
    (81, "Jordan Addison", "WR", "MIN"),
    (82, "Jaylen Warren", "RB", "PIT"),
    (83, "Harold Fannin Jr.", "TE", "CLE"),
    (84, "Justin Herbert", "QB", "LAC"),
    (85, "Tucker Kraft", "TE", "GB"),
    (86, "Jaxson Dart", "QB", "NYG"),
    # Tier 8
    (87, "Jakobi Meyers", "WR", "JAX"),
    (88, "Trevor Lawrence", "QB", "JAX"),
    (89, "Dak Prescott", "QB", "DAL"),
    (90, "Ricky Pearsall", "WR", "SF"),
    (91, "Sam LaPorta", "TE", "DET"),
    (92, "Kyle Pitts", "TE", "ATL"),
    (93, "J.K. Dobbins", "RB", "DEN"),
    (94, "Kyle Monangai", "RB", "CHI"),
    (95, "Makai Lemon", "WR", "PHI"),
    (96, "Blake Corum", "RB", "LAR"),
    (97, "Brock Purdy", "QB", "SF"),
    (98, "Michael Pittman Jr.", "WR", "PIT"),
    (99, "Chris Godwin Jr.", "WR", "TB"),
    (100, "Patrick Mahomes", "QB", "KC"),
    (101, "Quentin Johnston", "WR", "LAC"),
    (102, "Matthew Stafford", "QB", "LAR"),
    # Tier 9
    (103, "Jayden Reed", "WR", "GB"),
    (104, "Bo Nix", "QB", "DEN"),
    (105, "Kyler Murray", "QB", "ARI"),
    (106, "Wan'Dale Robinson", "WR", "NYG"),
    (107, "Josh Downs", "WR", "IND"),
    (108, "Aaron Jones Sr.", "RB", "MIN"),
    (109, "Jordan Love", "QB", "GB"),
    (110, "Jared Goff", "QB", "DET"),
    (111, "Dalton Kincaid", "TE", "BUF"),
    (112, "Oronde Gadsden II", "TE", "JAX"),
    (113, "George Kittle", "TE", "SF"),
    (114, "Jalen Coker", "WR", "CAR"),
    (115, "Dallas Goedert", "TE", "PHI"),
    (116, "KC Concepcion", "WR", "CLE"),
    (117, "Jake Ferguson", "TE", "DAL"),
    (118, "Khalil Shakir", "WR", "BUF"),
    (119, "Baker Mayfield", "QB", "TB"),
    (120, "Jacory Croskey-Merritt", "RB", "WSH"),
    (121, "Xavier Worthy", "WR", "KC"),
    # Tier 10
    (122, "Travis Kelce", "TE", "KC"),
    (123, "Matthew Golden", "WR", "GB"),
    (124, "Malik Willis", "QB", "GB"),
    (125, "Tyler Shough", "QB", "NO"),
    (126, "Romeo Doubs", "WR", "GB"),
    (127, "Chris Rodriguez Jr.", "RB", "JAX"),
    (128, "Jayden Higgins", "WR", "HOU"),
    (129, "Kenneth Gainwell", "RB", "PIT"),
    (130, "Kenyon Sadiq", "TE", "NYJ"),
    (131, "Sam Darnold", "QB", "SEA"),
    (132, "Jordan Mason", "RB", "MIN"),
    (133, "C.J. Stroud", "QB", "HOU"),
    (134, "Jalen McMillan", "WR", "TB"),
    (135, "Mark Andrews", "TE", "BAL"),
    (136, "Omar Cooper Jr.", "WR", "NYJ"),
    (137, "Tyrone Tracy Jr.", "RB", "NYG"),
    (138, "Daniel Jones", "QB", "IND"),
    (139, "Jonathon Brooks", "RB", "CAR"),
    (140, "Rachaad White", "RB", "TB"),
    (141, "Hunter Henry", "TE", "NE"),
    (142, "Jauan Jennings", "WR", "SF"),
    # Tier 11
    (143, "Isaiah Likely", "TE", "BAL"),
    (144, "Rashid Shaheed", "WR", "SEA"),
    (145, "Brian Robinson Jr.", "RB", "SF"),
    (146, "Brenton Strange", "TE", "JAX"),
    (147, "Woody Marks", "RB", "HOU"),
    (148, "Denzel Boston", "WR", "CLE"),
    (149, "Calvin Ridley", "WR", "TEN"),
    (150, "Houston Texans", "DST", "HOU"),
    (151, "Stefon Diggs", "WR", "NE"),
    (152, "Cam Ward", "QB", "CAR"),
    (153, "Juwan Johnson", "TE", "NO"),
    (154, "Brandon Aubrey", "K", "DAL"),
    (155, "Jerry Jeudy", "WR", "CLE"),
    (156, "Tre Tucker", "WR", "LV"),
    (157, "Bryce Young", "QB", "CAR"),
    (158, "T.J. Hockenson", "TE", "MIN"),
    (159, "Jacoby Brissett", "QB", "FA"),
    (160, "Tyler Allgeier", "RB", "ATL"),
    (161, "Tyjae Spears", "RB", "TEN"),
    (162, "Seattle Seahawks", "DST", "SEA"),
    (163, "Deebo Samuel Sr.", "WR", "WSH"),
    (164, "Germie Bernard", "WR", "PIT"),
    (165, "Isiah Pacheco", "RB", "DET"),
    (166, "Chig Okonkwo", "TE", "TEN"),
    (167, "Keaton Mitchell", "RB", "BAL"),
    (168, "Dalton Schultz", "TE", "HOU"),
    # Tier 12
    (169, "Cam Little", "K", "JAX"),
    (170, "Jacksonville Jaguars", "DST", "JAX"),
    (171, "Pittsburgh Steelers", "DST", "PIT"),
    (172, "Cooper Kupp", "WR", "LAR"),
    (173, "Pat Freiermuth", "TE", "PIT"),
    (174, "Emanuel Wilson", "RB", "GB"),
    (175, "Cade Otton", "TE", "TB"),
    (176, "Fernando Mendoza", "QB", "CHI"),
    (177, "Kayshon Boutte", "WR", "NE"),
    (178, "Isaac TeSlaa", "WR", "DET"),
    (179, "Braelon Allen", "RB", "NYJ"),
    (180, "Tank Bigsby", "RB", "PHI"),
    (181, "Dylan Sampson", "RB", "CLE"),
    (182, "Tyreek Hill", "WR", "MIA"),
    (183, "Jalen Nailor", "WR", "LV"),
    (184, "Gunnar Helm", "TE", "HOU"),
    (185, "Ray Davis", "RB", "BUF"),
]

rows = []
for rb_pos_rank_by_pos, (overall, name, pos, team) in enumerate(players, 1):
    rows.append({
        "player":          name,
        "position":        pos,
        "team":            team,
        "rb_overall_rank": overall,
    })

df = pd.DataFrame(rows)

# Add position ranks
df["rb_pos_rank"] = df.groupby("position")["rb_overall_rank"].rank(method="first").astype(int)

path = os.path.join("data","2026","rotoballer.csv")
df.to_csv(path, index=False)
print(f"✅ RotoBaller updated → {path}")
print(f"   {len(df)} players")
print(df.head(10).to_string(index=False))
